import { Talk } from "@/app/PastTalkList";
import { Welcome } from "@/app/Welcome";
import Head from "next/head";
// import Image from 'next/image'
// import { Inter } from '@next/font/google'
// import styles from '@/styles/Home.module.css'

import { Navigation } from "../app/Navigation";

// const inter = Inter({ subsets: ['latin'] })

export default function Home({ pastTalks }: { pastTalks: Talk[] }) {
  return (
    <>
      <Head>
        <title>Chennai Dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Welcome pastTalks={pastTalks} />
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch(
    "https://strapi-cms-api-eu.onrender.com/api/past-talks?populate[speaker][populate]=*&populate[cover][url]&populate[references]=*"
  );
  const strapiData = await res.json();
  const pastTalks: Talk[] = strapiData.data?.map((dt) => dt.attributes);

  console.log(pastTalks);

  return {
    props: { pastTalks },
  };
}
