import { Talk } from "@/app/PastTalkList";
import { Welcome } from "@/app/Welcome";
import Head from "next/head";
// import Image from 'next/image'
// import { Inter } from '@next/font/google'
// import styles from '@/styles/Home.module.css'

import { Navigation } from "../app/Navigation";

// const inter = Inter({ subsets: ['latin'] })

// Generated by https://quicktype.io

const API = `https://strapi-cms-api-eu.onrender.com`;
// const API = `http://localhost:1337`;

export interface MeetupDetail {
  date: string;
  fromTime: string;
  endTime: string;
  registrationLink: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  venue: Venue;
}

export interface Venue {
  data: Data;
}

export interface Data {
  id: number;
  attributes: Attributes;
}

export interface Attributes {
  name: string;
  mapLink: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
}

export default function Home({
  pastTalks,
  meetupDetails,
}: {
  pastTalks: Talk[];
  meetupDetails: MeetupDetail[];
}) {
  return (
    <>
      <Head>
        <title>Chennai Dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Welcome pastTalks={pastTalks} meetupDetails={meetupDetails} />
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch(
    `${API}/api/past-talks?populate[speaker][populate]=*&populate[cover][url]&populate[references]=*`
  );
  const strapiData = await res.json();
  const pastTalks: Talk[] = strapiData.data?.map(
    (dt: { attributes: Talk }) => dt.attributes
  );

  const res1 = await fetch(`${API}/api/meetup-details?populate=*`);
  const strapiData1 = await res1.json();
  const meetupDetails: MeetupDetail[] = strapiData1.data?.map(
    (dt: { attributes: MeetupDetail }) => dt.attributes
  );

  console.log("🤩🤩", meetupDetails);

  return {
    props: { pastTalks, meetupDetails },
  };
}
